name: tests-categories

on: 
  pull_request

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd categories && npm install && npm run test:ci
    
